# Website title & description (the description is used in the HTML <head>, read by Google and co)
title: Philippe Cadene
description: >

  My name is Philippe Cadene. I am Emeritus Professor at Université Paris Cité, France, where I taught for more than two decades Economic Geography, Regional Studies and Development Studies
  
# Your personal infos (used for the sidebar)
author:
  # Site title
  name: Philippe Cadene
  # _includes/header.html
  description: Emeritus Professor, Economic Geography and Development Studies - Departement of Geography - Université Paris Cité- GHES School - Researcher at CESSMA
  photo: /images/photo.jpg
  # Contacts (will be used by the contact block, you can enter everything here and choose which one should appear there)
  email: philippe.cadene@u-paris.fr
  phone: +33 6 03 03 18 28
  address: "Pr. Philippe Cadene \n CESSMA Université Paris Cité\n Case courrier 7017 \n 75205 PARIS CEDEX 13 \n France"
  twitter: username
  linkedin: username
  github: username
  google-plus: username


# Link that appear at the top of the sidebar to return to the "main" site of the team, remove lines below to remove link
#back-link:
#  url: http://philippecadene.fr
#  title: Multimedia team


# Technical infos
baseurl: "" # url of your webpage if not at the root of the domain (leading /, no trailing /)
url: "http://philippecadene.fr" # the base hostname & protocol for your site (no trailing /)
header-default-style: trianglify # default page header style (see styles in user documentation)
# google-analytics: UA-XXXXXXX-X # your google analytics code if you want visit stats (uncomment to enter)


# "Very" technical infos (modify only if you know what you're doing)
sass:
  sass_dir: /assets/css/
  style: compressed
timezone: Europe/Paris
include: ['_pages']
permalink: /:title/
collections:
  - homepage
onepage-default-collection: homepage
defaults:
  # default layout for pages is "page", and link is only filename without "_pages/"
  - scope:
      path: _pages
    values:
      order: 50 # Default order value at 50 so that you can force some pages to appear at the end without setting the order for all of them
      layout: page
      permalink: /:basename/
  # default layout for homepage blocks is "onepage-block"
  - scope:
      type: homepage
    values:
      layout: onepage-block
